name: Build and Deploy React App

on:
  push:
    branches:
      - main

permissions:
  id-token: write # allows the JWT to be requested from GitHub's OIDC provider
  contents: read # This is required for actions/checkout

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Setup Node.js with .nvmrc
      uses: actions/setup-node@v4.0.1
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: yarn install

    - name: Build React App with Vite
      run: yarn build

    - name: Assume IAM Role and Set AWS Credentials
      id: assume-role
      uses: aws-actions/configure-aws-credentials@v4.0.1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
        role-duration-seconds: 900 # Adjust as needed

    - name: Synchronize with S3 and Invalidate CloudFront
      run: |
        cd dist
        aws s3 sync . s3://transformers-workflow-engine --delete
        aws cloudfront create-invalidation --distribution-id E2PO7XUKI9DBAP --paths "/*"
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ steps.assume-role.outputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ steps.assume-role.outputs.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ steps.assume-role.outputs.AWS_SESSION_TOKEN }}
